### PR TITLE
Add persistent subscription info support

### PR DESCRIPTION
**Pull request by kristofka**
I've tried to abide by the coding standards. However, I'm not sure how and where to implement the tests.

Let me know how I can improve this request.

### CODE REVIEW

**Comment by the-mikedavis** [comment]
This is looking good 😀

I think this just needs a test in `test/spear_test.exs` (around L292 or within that `describe` block):

```elixir
@tag compatible(">= 22.10.0")
test "info about a psub can be fetched", c do
  stream = c.stream_name
  group = uuid_v4()
  settings = %Spear.PersistentSubscription.Settings{}

  assert Spear.create_persistent_subscription(c.conn, stream, group, settings) == :ok

  assert {:ok, %Spear.PersistentSubscription.Info{event_source: ^stream, group_name: ^group}} =
           Spear.get_persistent_subscription_info(c.conn, stream, group)
end
```

**Comment by kristofka** [comment]
Oops, had a couple of mistakes in the tests. Should be fixed. Sorry about that.

**Comment by kristofka** [comment]
I'm not sure how I've broken two unrelated tests. Could it be the CI runner? I'm a bit lost here, sorry.

**Comment by the-mikedavis** [comment]
Oh hmm I think those two are a little flaky. Let me give them a restart

**Comment by kristofka** [comment]
Reformatted `spear.ex` - mix format is adament that case clauses should be separated by an empty line. 
Should be fixed.
Thank you for your patience.

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Looks good, thanks! I'll check out the other new RPCs and see if we can bundle all of the new ones into a new minor release

**Comment by the-mikedavis** [comment]
This is now released in v1.2.0 🎉

**Comment by kristofka** [comment]
Thank you for your work and help. Much appreciated!

**Pull request merged**
